language: go

go:
  - 1.11.x

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

env:
  - CODECOV_TOKEN=e0993bb5-cd6c-4625-9270-d36ac73136d0

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

